/**
 * Build-time script: pre-compute light/dark color variables.
 * Run before `tsc` via `pnpm run generate`.
 */
import { writeFileSync, mkdirSync } from 'fs'
import { dirname, join } from 'path'
import { generateColors } from '../src/index'

const outPath = join(process.cwd(), 'src/precomputed/colors.ts')

const lightColors = generateColors('light')
const darkColors = generateColors('dark')

const formatObject = (obj: Record<string, string>, indent: string): string => {
  const entries = Object.entries(obj)
    .map(([key, value]) => `${indent}  '${key}': '${value}',`)
    .join('\n')
  return `{\n${entries}\n${indent}}`
}

const content = `// AUTO-GENERATED by scripts/generate-precomputed.ts — do not edit manually.
// Re-run \`pnpm run generate\` after changing color generation logic.

export type ColorVariables = Record<string, string>

export const lightColors: ColorVariables = ${formatObject(lightColors, '')}

export const darkColors: ColorVariables = ${formatObject(darkColors, '')}
`

mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, content, 'utf-8')

console.log(`Generated ${outPath} (${Object.keys(lightColors).length} light / ${Object.keys(darkColors).length} dark variables)`)
