name: Release
on:
    push:
        branches:
            - main
            - pre/**

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # 获取完整提交历史

            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Recursive installation of all package dependencies
              run: pnpm install -r

            - name: Build Packages
              run: pnpm run build

            - name: Creating .npmrc
              run: |
                  cat << EOF > "$HOME/.npmrc"
                    //registry.npmjs.org/:_authToken=$NPM_TOKEN
                  EOF
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Create Release
              uses: changesets/action@v1
              with:
                  title: "Update Release Packages Version"
                  commit: "chore: packages version"
                  publish: pnpm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
